# Generated by Django 5.0.4 on 2024-06-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data']},
        ),
    ]
