version: "3.9"

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: lovegav
      POSTGRES_USER: django_admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  lovegavapp:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c '/wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8080'
    ports:
      - "8000:8080"
    environment:
      - DATABASE_NAME=lovegav
      - DATABASE_USER=django_admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
volumes:
  db_data: