# Generated by Django 5.0.2 on 2024-04-23 13:14

import django.db.models.deletion
import profileapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Famale')], max_length=1)),
                ('specie', models.CharField(blank=True, max_length=20, null=True)),
                ('breed', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('chip', models.BooleanField(blank=True, null=True)),
                ('tatoo', models.TextField(blank=True, max_length=20)),
                ('date_tatoo', models.DateField(blank=True, null=True)),
                ('passport', models.FileField(null=True, upload_to=profileapp.models.pet_files_path)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
