# Generated by Django 5.0.2 on 2024-05-03 13:05

import profileapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_pet_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=profileapp.models.pet_files_path),
        ),
        migrations.AlterField(
            model_name='pet',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=profileapp.models.pet_files_path),
        ),
    ]
