# Generated by Django 5.0.4 on 2024-06-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name']},
        ),
    ]
