# Generated by Django 5.0.4 on 2024-06-27 12:04

import profileapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0010_alter_pet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=profileapp.models.profile_avatar_directory_path),
        ),
    ]
