# Generated by Django 5.0.2 on 2024-04-26 15:30

import functionalapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(null=True, upload_to=functionalapp.models.playgrounds_photo_path)),
            ],
        ),
    ]
