# Generated by Django 5.0.2 on 2024-04-27 08:55

import django.db.models.deletion
import functionalapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('data', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(null=True, upload_to=functionalapp.models.questions_photo_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('data', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(null=True, upload_to=functionalapp.models.questions_photo_path)),
                ('answers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='functionalapp.answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
