# Generated by Django 5.0.2 on 2024-04-27 09:03

import functionalapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalapp', '0002_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=functionalapp.models.questions_photo_path),
        ),
    ]
