# Generated by Django 5.0.2 on 2024-05-02 09:18

import functionalapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalapp', '0004_alter_question_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=functionalapp.models.questions_photo_path),
        ),
    ]
