# Generated by Django 5.0.2 on 2024-05-02 12:10

import functionalapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalapp', '0006_remove_question_answers_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=functionalapp.models.answers_photo_path),
        ),
    ]
